Hello, my name is Margarita Iankova. I'm going to review your project!

You can find my comments in <span style="color:green">green</span>,<span style="color:blue">blue</span> or <span style="color:red">red</span> boxes like this:

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> if everything is done succesfully
</div>

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> if I can give some recommendations
</div>

<div class="alert alert-danger" style="box-shadow: 4px 4px 4px">
<b>Needs fixing:</b> if the block requires some corrections. Work can't be accepted with the red comments.
</div>

<div class="alert alert-danger" style="box-shadow: 4px 4px 4px">
<s><h2> General feedback</h2>
<b>Needs fixing:</b> You did a great job, but I would like to ask you to fix something. It does not take much time. Replace all comments in your code with markdown to make them more readable.
    <br> Also, in your work, you often duplicate similar code, output tables, and a large number of prints. It's not bad when you're working on a project, but it's better to fix it in the final version. You will find my comments along the way!
    <br>Otherwise, your research is very well done!
    
</div>

Hello, Margarita, nice to e-meet you! Thank you very much for reviewing my project thoroughly. 
I worked according to your advice and comments. I learned a lot. 

* Markdown - I didn't know things that I could do with this feature. 
* Empty values and large positive values ('days_employed') - I learned the way to handle them separately. 
* '-1' and '20' ('children') - I learned another, more common way of interpreting these kinds of values. 
* Code verification - I commented them out because I didn't want to remove them. Hope that's OK. 

Also, 
* I added the final conclusion that summarizes the answers to the four questions being asked to the Global Conclusion section. 
* could you please let me know your answer to this question?
<br>[QUESTION] How can I keep 'wedding' (before lemmatization) but unify 'car' and 'cars' (after lemmatization)?

I would appreciate it if you could review my work one more time (hope this will be the last). 

Much appreciated! 

Rena

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<h1> General feedback </h1> 
    <br> Good job, now everything is great! You took the research very seriously, I want to praise you for your detailed comments. I congratulate you, your project has been accepted!
    <br>I left a comment about lemmatization where you use it. In general, usually lemmatizing and finfing the stem of a word means removing the ending 'ing', so, such words have to be processed manually
</div>

  
# Analyzing borrowers’ risk of defaulting

Your project is to prepare a report for a bank’s loan division. You’ll need to find out if a customer’s marital status and number of children has an impact on whether they will default on a loan. The bank already has some data on customers’ credit worthiness.

Your report will be considered when building a **credit scoring** of a potential customer. A ** credit scoring ** is used to evaluate the ability of a potential borrower to repay their loan.

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Great! A good introduction leads to a good job! In addition, you can add the main goal and a project plan.
</div>

## Open the data file and have a look at the general information. 

In [108]:
# Import the pandas library.
import pandas as pd
import numpy as np

# Import NLTK
import nltk
# nltk.download('punkt')
from nltk.stem import SnowballStemmer
english_stemmer = SnowballStemmer('english')

from nltk.stem import WordNetLemmatizer
wordnet_lemma = WordNetLemmatizer() 
# nltk.download('wordnet')

from nltk.corpus import stopwords
# nltk.download('stopwords')

# Import sys so no warnings will be issued. 
import sys
if not sys.warnoptions:
    import warnings
    warnings.simplefilter("ignore")

[Overview]  
Does a person's marital status and the number of children s/he has impact on whether s/he will default on a loan? 
We will analyse the data provided by our client, a bank's Loan Division, on their customers, and produce 
a report which will be used to figure out a potential customer's credit score for evaluating his/her ability to repay a loan.

[Goals] 
Find the answer(s) to the following questions:
1. Is there a connection between having kids and repaying a loan on time?
2. Is there a connection between marital status and repaying a loan on time?
3. Is there a connection between income level and repaying a loan on time?
4. How do different loan purposes affect on-time loan repayment?

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> I am impressed by your comments on the work: keep it up!
</div>

<div class="alert alert-danger" style="box-shadow: 4px 4px 4px">
<s><b>Needs fixing:</b> Here and later, I will ask you to move all non-code notes to markdown. So the text will be more readable and understandable.
</div>

### Load the data csv file.

In [109]:
# I worked locally and will have to upload the project to the Platform. So cover both paths. 
try:
    data = pd.read_csv('credit_scoring_eng.csv')
except:
    data = pd.read_csv('/datasets/credit_scoring_eng.csv')

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Well done for using try ... except!
</div>

### Explore the data and make some preliminary observations.

In [110]:
# View the first 5 rows to see what the data look like.
data.head()

children  days_employed  dob_years            education  education_id  \
0         1   -8437.673028         42    bachelor's degree             0   
1         1   -4024.803754         36  secondary education             1   
2         0   -5623.422610         33  Secondary Education             1   
3         3   -4124.747207         32  secondary education             1   
4         0  340266.072047         53  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   

                   purpose  
0    purchase of the house  
1             car purchase  
2    purchase of the house  
3  supplementary education  
4        to have a wedding

Total number of variables: 12
1. children: the number of children in the family
2. dob_years: the customer’s age
3. days_employed: how long the customer has been working prior to the loan application (in days)
4. education: the customer’s education level
5. education_id: identifier for the customer’s education 
6. family_status: the customer’s marital status
7. family_status_id: identifier for the customer’s marital status
8. gender: the customer’s gender
9. income_type: the customer’s income type
10. debt: 1 - has defaulted on a loan in the past; 0 - repaid successfully
11. total_income: monthly income
12. purpose: reason for asking for a loan

[Observations] 
* 'days_employed': there are negative values; there are astronomical positive values (340266.072047 days ~= 932 years!!) (-> Deep dive)
* 'education': capitalization and cases are mixed. Should be standardised to lowercase (-> Change data types). 
* 'dob_years': better to rename to 'age' for clarity (-> Rename variable). 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Good points
</div>

In [111]:
# Get some general info on the data. 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


Total number of rows: 21525 

[Observations]
* 'days_employed': the float data type should be changed to int (-> Change data types). 
* 'debt': the int data type should be changed to boolean  (-> Change data types).
* 'days_employed', 'total_income': both have 2174 (=21525-19351) missing values (-> Missing values).

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Agree
</div>

In [112]:
# Get some more general info on the quantitative data. 
data.describe()

children  days_employed     dob_years  education_id  \
count  21525.000000   19351.000000  21525.000000  21525.000000   
mean       0.538908   63046.497661     43.293380      0.817236   
std        1.381587  140827.311974     12.574584      0.548138   
min       -1.000000  -18388.949901      0.000000      0.000000   
25%        0.000000   -2747.423625     33.000000      1.000000   
50%        0.000000   -1203.369529     42.000000      1.000000   
75%        1.000000    -291.095954     53.000000      1.000000   
max       20.000000  401755.400475     75.000000      4.000000   

       family_status_id          debt   total_income  
count      21525.000000  21525.000000   19351.000000  
mean           0.972544      0.080883   26787.568355  
std            1.420324      0.272661   16475.450632  
min            0.000000      0.000000    3306.762000  
25%            0.000000      0.000000   16488.504500  
50%            0.000000      0.000000   23202.870000  
75%            1.000000      0.000000   32549.611000  
max            4.000000      1.000000  362496.645000

[Observations]
* 'children': -1 children? A clerical error? A child death?; 20 children? This is a high-end outlier. (-> Deep dive)
* 'dob_years': why are 0-year-old babies asking for a loan? A clerical error? Customers not wanting to reveal their age? (-> Deep dive)
* 'total_income': no negative values

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> 😂 Nice!
</div>

<div class="alert alert-danger" style="box-shadow: 4px 4px 4px">
<s><b>Needs fixing:</b> Remember about comments style
</div>

Let's see what kind of values are there in each column. 

Note: skipping this step for 'days_employed' and 'total_income' since the lists are too long and cannot spot anomalies this way. 

In [113]:
# View the unique values in the 'children' column. 
data.children.unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5])

In [114]:
# View the unique values in the 'dob_years' column. 
data.dob_years.unique()

array([42, 36, 33, 32, 53, 27, 43, 50, 35, 41, 40, 65, 54, 56, 26, 48, 24,
       21, 57, 67, 28, 63, 62, 47, 34, 68, 25, 31, 30, 20, 49, 37, 45, 61,
       64, 44, 52, 46, 23, 38, 39, 51,  0, 59, 29, 60, 55, 58, 71, 22, 73,
       66, 69, 19, 72, 70, 74, 75])

[Observation] no anomalies

In [115]:
# View the unique values in the 'education' column. 
data.education.unique()

array(["bachelor's degree", 'secondary education', 'Secondary Education',
       'SECONDARY EDUCATION', "BACHELOR'S DEGREE", 'some college',
       'primary education', "Bachelor's Degree", 'SOME COLLEGE',
       'Some College', 'PRIMARY EDUCATION', 'Primary Education',
       'Graduate Degree', 'GRADUATE DEGREE', 'graduate degree'],
      dtype=object)

[Observation] there are duplicates due to mixed cases (-> Change data types).

In [116]:
# View the unique values in the 'education_id' column. 
data.education_id.unique()

array([0, 1, 2, 3, 4])

[Observation] no anomalies

In [117]:
# View the unique values in the 'family_status' column. 
data.family_status.unique()

array(['married', 'civil partnership', 'widow / widower', 'divorced',
       'unmarried'], dtype=object)

[Observation] all the values are in lowercase. 

In [118]:
# View the unique values in the 'family_status_id' column. 
data.family_status_id.unique()

array([0, 1, 2, 3, 4])

[Observation] no anomalies

In [119]:
# View the unique values in the 'gender' column. 
data.gender.unique()

array(['F', 'M', 'XNA'], dtype=object)

[Observation] no anomalies

In [120]:
# View the unique values in the 'income_type' column. 
data.income_type.unique()

array(['employee', 'retiree', 'business', 'civil servant', 'unemployed',
       'entrepreneur', 'student', 'paternity / maternity leave'],
      dtype=object)

[Observation] all the values are in lowercase. 

In [121]:
# View the unique values in the 'debt' column. 
data.debt.unique()

array([0, 1])

In [122]:
# View the unique values in the 'purpose' column. 
data.purpose.unique()

array(['purchase of the house', 'car purchase', 'supplementary education',
       'to have a wedding', 'housing transactions', 'education',
       'having a wedding', 'purchase of the house for my family',
       'buy real estate', 'buy commercial real estate',
       'buy residential real estate', 'construction of own property',
       'property', 'building a property', 'buying a second-hand car',
       'buying my own car', 'transactions with commercial real estate',
       'building a real estate', 'housing',
       'transactions with my real estate', 'cars', 'to become educated',
       'second-hand car purchase', 'getting an education', 'car',
       'wedding ceremony', 'to get a supplementary education',
       'purchase of my own house', 'real estate transactions',
       'getting higher education', 'to own a car', 'purchase of a car',
       'profile education', 'university education',
       'buying property for renting out', 'to buy a car',
       'housing renovation', 'going

[Observation] all the values are in lowercase. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> You are very serious about data analysis: well done! We need to be alert while working with data
</div>

### Investigate the observations (Deep dive). 

**Try to find a pattern or logic behind the odd values in the 'children' column.**

In [123]:
# Look at the first 10 of the 47 rows. 
data[data['children'] < 0].head(10)

children  days_employed  dob_years            education  education_id  \
291         -1   -4417.703588         46  secondary education             1   
705         -1    -902.084528         50  secondary education             1   
742         -1   -3174.456205         57  secondary education             1   
800         -1  349987.852217         54  secondary education             1   
941         -1            NaN         57  Secondary Education             1   
1363        -1   -1195.264956         55  SECONDARY EDUCATION             1   
1929        -1   -1461.303336         38  secondary education             1   
2073        -1   -2539.761232         42  secondary education             1   
3814        -1   -3045.290443         26  Secondary Education             1   
4201        -1    -901.101738         41  secondary education             1   

          family_status  family_status_id gender    income_type  debt  \
291   civil partnership                 1      F       employee     0   
705             married                 0      F  civil servant     0   
742             married                 0      F       employee     0   
800           unmarried                 4      F        retiree     0   
941             married                 0      F        retiree     0   
1363            married                 0      F       business     0   
1929          unmarried                 4      M       employee     0   
2073           divorced                 3      F       business     0   
3814  civil partnership                 1      F  civil servant     0   
4201            married                 0      F  civil servant     0   

      total_income                           purpose  
291      16450.615                 profile education  
705      22061.264                      car purchase  
742      10282.887           supplementary education  
800      13806.996           supplementary education  
941            NaN                 buying my own car  
1363     11128.112                 profile education  
1929     17459.451             purchase of the house  
2073     26022.177             purchase of the house  
3814     21102.846                  having a wedding  
4201     36220.123  transactions with my real estate

In [124]:
# Look at the last 10 of the 47 rows. 
data[data['children'] < 0].tail(10)

children  days_employed  dob_years            education  education_id  \
17095        -1   -2809.693200         34  secondary education             1   
17429        -1    -895.379738         37  secondary education             1   
17657        -1   -4571.957475         41  secondary education             1   
18219        -1   -3575.215641         33  secondary education             1   
19100        -1    -617.246968         38  secondary education             1   
19366        -1    -372.034749         43  SECONDARY EDUCATION             1   
19417        -1  350340.760224         28  secondary education             1   
20393        -1  355157.107212         69  secondary education             1   
20717        -1    -661.822321         32    bachelor's degree             0   
21140        -1   -1422.668059         44  secondary education             1   

      family_status  family_status_id gender income_type  debt  total_income  \
17095       married                 0      F    employee     0     29207.022   
17429       married                 0      F    business     0     34370.243   
17657       married                 0      F    employee     0     19536.867   
18219       married                 0      F    employee     0     20537.924   
19100     unmarried                 4      M    employee     0     19552.880   
19366       married                 0      M    employee     0     24894.203   
19417      divorced                 3      F     retiree     0      8459.679   
20393     unmarried                 4      F     retiree     0     18643.367   
20717       married                 0      F    employee     0     21984.862   
21140       married                 0      F    business     0     27129.935   

                                purpose  
17095          buying a second-hand car  
17429                           housing  
17657  transactions with my real estate  
18219              university education  
19100            building a real estate  
19366          second-hand car purchase  
19417                              cars  
20393          real estate transactions  
20717       buy residential real estate  
21140  transactions with my real estate

[Observation] Cannot establish a clear pattern. Since we cannot get in touch with the data owner or the data engineer, we can only guess. 
1. Probably, '-1' is a clerical error rather than a record of a child death. (-> Treat it as a '1')
2. '20' can be either "more than 5 children" or a clerical error. The latter is more plausible. (-> Treat it as a '2') 

**Try to find a pattern or logic behind the odd values in the 'days_employed' column.**

In the financial industry, 
* a negative value refers to the number of days a person was employed up until the loan application date. 
* a high positive value signifies NaN/Unknown. 

In [125]:
# View the first 10 of the high positive values. 
data[data['days_employed'] > 0].head(10)

children  days_employed  dob_years            education  education_id  \
4          0  340266.072047         53  secondary education             1   
18         0  400281.136913         53  secondary education             1   
24         1  338551.952911         57  secondary education             1   
25         0  363548.489348         67  secondary education             1   
30         1  335581.668515         62  secondary education             1   
35         0  394021.072184         68  secondary education             1   
50         0  353731.432338         63  secondary education             1   
56         0  370145.087237         64  secondary education             1   
71         0  338113.529892         62  secondary education             1   
78         0  359722.945074         61    bachelor's degree             0   

        family_status  family_status_id gender income_type  debt  \
4   civil partnership                 1      F     retiree     0   
18    widow / widower                 2      F     retiree     0   
24          unmarried                 4      F     retiree     0   
25            married                 0      M     retiree     0   
30            married                 0      F     retiree     0   
35  civil partnership                 1      M     retiree     0   
50            married                 0      F     retiree     0   
56    widow / widower                 2      F     retiree     0   
71            married                 0      F     retiree     0   
78            married                 0      M     retiree     0   

    total_income                                   purpose  
4      25378.572                         to have a wedding  
18      9091.804                  buying a second-hand car  
24     46487.558  transactions with commercial real estate  
25      8818.041                           buy real estate  
30     27432.971  transactions with commercial real estate  
35     12448.908                          having a wedding  
50     14774.837                                      cars  
56     23862.567                                 education  
71      7028.751                                      cars  
78     28020.423                         purchase of a car

[Observation] 
Seem to be all "secondary education" in 'education' and "retiree" in 'income_type'. (-> Deep dive)

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Better not to conclude from an incomplete dataset
</div>



In [126]:
# Check how many high positive values there are. 
data[data['days_employed'] > 0].count()

children            3445
days_employed       3445
dob_years           3445
education           3445
education_id        3445
family_status       3445
family_status_id    3445
gender              3445
income_type         3445
debt                3445
total_income        3445
purpose             3445
dtype: int64

[Observation] 
A total of 3445 high positive values.

In [127]:
# Check if all those with 'secondary education' were assigned a high positive value in 'days_employed'.
data[data['days_employed'] > 0]['education'].value_counts()

secondary education    2511
bachelor's degree       471
Secondary Education     148
SECONDARY EDUCATION     135
primary education        82
some college             31
BACHELOR'S DEGREE        29
Bachelor's Degree        21
PRIMARY EDUCATION         7
Primary Education         4
Some College              3
graduate degree           1
Graduate Degree           1
SOME COLLEGE              1
Name: education, dtype: int64

[Observation] There are 2794 (= 2511+148+135) "secondary education" entries in various formats. This is not close to 3445. So, no, that is not the case.

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Your code doesn't quite match the comment. If you want to check the statement above, then you should either count the total number of people with 'secondary education and compare it with the obtained value or try another way to filter the data by education
</div>



In [128]:
# Check if all those with 'retiree' are assigned a high positive value in 'days_employed'.
data[data['days_employed'] > 0]['income_type'].value_counts()

retiree       3443
unemployed       2
Name: income_type, dtype: int64

[Observation] The majority is 'retiree'. This is very close to 3445. Is this a way of marking a 'retiree'...? The 2 'unemployed' are clerical slip-ups?

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Same
</div>



**Try to find a pattern or logic behind the odd values in the 'dob_years' column.**

In [129]:
# Check how many times '0' appears.
data[data['dob_years'] == 0].count()

children            101
days_employed        91
dob_years           101
education           101
education_id        101
family_status       101
family_status_id    101
gender              101
income_type         101
debt                101
total_income         91
purpose             101
dtype: int64

[Observation] There are 101 '0' entries. 

In [130]:
# View the first 10 of the 101 rows. 
data[data['dob_years'] == 0].head(10)

children  days_employed  dob_years            education  education_id  \
99           0  346541.618895          0  Secondary Education             1   
149          0   -2664.273168          0  secondary education             1   
270          3   -1872.663186          0  secondary education             1   
578          0  397856.565013          0  secondary education             1   
1040         0   -1158.029561          0    bachelor's degree             0   
1149         0    -934.654854          0  secondary education             1   
1175         0  370879.508002          0  secondary education             1   
1386         0   -5043.219890          0    bachelor's degree             0   
1890         0            NaN          0    bachelor's degree             0   
1898         0  370144.537021          0  secondary education             1   

        family_status  family_status_id gender    income_type  debt  \
99            married                 0      F        retiree     0   
149          divorced                 3      F       employee     0   
270           married                 0      F       employee     0   
578           married                 0      F        retiree     0   
1040         divorced                 3      F       business     0   
1149          married                 0      F       business     0   
1175          married                 0      F        retiree     0   
1386          married                 0      M  civil servant     0   
1890        unmarried                 4      F       employee     0   
1898  widow / widower                 2      F        retiree     0   

      total_income                           purpose  
99       11406.644                               car  
149      11228.230              housing transactions  
270      16346.633                housing renovation  
578      15619.310      construction of own property  
1040     48639.062                      to own a car  
1149     32296.389                   buy real estate  
1175     50231.975  to get a supplementary education  
1386     38483.779                 purchase of a car  
1890           NaN                           housing  
1898     20384.043                      to buy a car

[Observation] No obvious pattern jumps at me. 

In my research on loan eligibility in terms of age, the minimum lower boundary and the maximum upper boundary I saw were 18 and 76, respectively. So in our client's case, it looks like the range is 19-75.
<br>
<br>[Observation] So a 0 may indicate those applicants who are outside that age range.

### Conclusion

'days_employed' 
* The float data type should be changed to int. (-> Change data types)
* There are negative values.
* There are high positive values (340266.072047 days ~= 932 years!!) 
* The high positive values are all assigned to 'income_type' = 'retiree', with 2 exceptions in 'unemployed' (perhaps a clerical error). 
<br>Note: In the financial industry, 
* a negative value refers to the number of days employed up until the loan application date. 
* a high positive value signifies NaN/Unknown. 

'education' 
* Capitalization and cases are mixed. Should be standardised to lowercase. (-> Change data types)

'dob_years'
* Better to rename to 'age' for clarity. (-> Rename variable)
* '0' probably indicates the applicants are not eligible for a loan because they are outside the permitted age range. 

'debt' 
* The int data type should be changed to boolean. (-> Change data types)

'days_employed', 'total_income'
* Both have 2174 (=21525-19351) missing values. (-> Investigate further)

'children'
* -1 children: probably a clerical error; handle it as a '1'. (-> Change the value)
* 20 children: probably a clerical error, too; handle it as a '2'. (Change the value)

Verified:
* No negative values: 'total_income', 'dob_years'
* No anomalies: 'education_id', 'family_status_id', 'gender'
* All in lowercase: 'family_status', 'income_type', 'purpose'

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> I really like your conclusions, everything is clear and structured!
</div>

<div class="alert alert-danger" style="box-shadow: 4px 4px 4px">
<s><b>Needs fixing:</b> 
Just to remind you of comment style ...
</div>

## Data preprocessing

### Processing missing values

**Determine how to fill missing values in such a way that the general characteristics of the dataset are maintained, and fill them.**

The 'days_employed' and 'total_income' columns were the only columns with missing values. 
<br>[Observation] Are the two columns missing values in exactly the same rows?

In [131]:
# Count the rows where both 'days_employed' and 'total_income' columns have missing values. 
data[data['days_employed'].isnull() & data['total_income'].isnull()].count()

children            2174
days_employed          0
dob_years           2174
education           2174
education_id        2174
family_status       2174
family_status_id    2174
gender              2174
income_type         2174
debt                2174
total_income           0
purpose             2174
dtype: int64

[Observation] The two columns are missing values in exactly the same rows. 
These customers are not working so there are neither 'days_employed' nor 'total_income' data? Or they just didn't want to reveal the information?

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Good!
</div>

In [132]:
# Divide the number of missing values per column by the size of the dataset to see the ratio of the missing values. 
data.isnull().sum() / len(data)

children            0.000000
days_employed       0.100999
dob_years           0.000000
education           0.000000
education_id        0.000000
family_status       0.000000
family_status_id    0.000000
gender              0.000000
income_type         0.000000
debt                0.000000
total_income        0.100999
purpose             0.000000
dtype: float64

[Observation] Approx. 10% of the rows are missing values in the two columns.

**Handle the missing values in the 'days-employed' column.**

Are there high positive values that indicate a "normal" number of years? 

In [133]:
# Check the minimum positive value.
data[data['days_employed'] > 0].min()

children                             -1
days_employed                    328729
dob_years                             0
education             BACHELOR'S DEGREE
education_id                          0
family_status         civil partnership
family_status_id                      0
gender                                F
income_type                     retiree
debt                                  0
total_income                    3306.76
purpose             building a property
dtype: object

[Observation] 328729 days are ~900 years!! 
So it is safe to conclude there is no positive value that indicates the number of days *since* the load application date.

So, in the 'days_employed' column, there are:
<br>a) 2174 missing values containing NaN,
<br>b) 3445 positive values, and
<br>c) 15906 (=21525-(2174+3445)) negative values.

[Observation] Only the negative values (c) are relevant to our research. Relate to the rest as 'missing values' (a, b). 

[Comment] I will try not to change the original data in future and save the new data in a new column since I never know when I will need them again. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Good observations!
</div>

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Answering your questions:
        <br> *  I usually save the changed data to a new column to accommodate the changes. But this is not necessary. You can leave new data in the old column if you are sure that you will not return to the old ones.
    <br> * You can just assign np.nan instead of 999999.99

</div>


In [134]:
# Replace the high positive values with NaN. NaN is a float type, and mathematical operations can be performed.
data.loc[data['days_employed'] > 0, 'days_employed'] = np.NaN

# Verify it worked. 
#data.days_employed.head(10)

[Observation] This brings up the ratio of missing values in the column from 10% to 26% (= 5619 / 21525). In general, up to 30% is acceptable and no need to drop the rows which are missing values, though there are no hard-and-fast rules. 

[Comment] I managed without using 999999.99 this time! :)

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Agree
</div>

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Answering your question:
        <br> * There is no clear line when dropping rows is necessary. But in general, 30% missing values ​​are acceptable.


</div>


In [135]:
# Convert the negative values to number of years by applying abs() then dividing by 365. 
data['days_employed_years'] = data['days_employed'].abs() / 365

# Verify it worked. 
#data.days_employed_years.head(10)

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> To get rid of negative values ​​it is better to use the abs() method


</div>

Unlike 'age', 'days_employed' is not something that everyone has. I cannot invent the number of days a person worked. 
If I were to fill the values with the mean or the median of the column, it will change the data significantly. 
The data are probably missing because the customers did not work or did not want to reveal the information (i.e. MNAR). 
I will handle them as a case where no data were provided. 

In [136]:
# So, fill the 'days_employed_years' column with zeros where there is NaN. 
data['days_employed_years'] = data['days_employed_years'].fillna(0)

# Verify it worked. 
#print(data.days_employed_years.head(10))
#data.days_employed_years.isnull().sum()

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> A good note about the mean and the median, but don't you confess that 30% of zeros will also significantly affect the data?
<br>
It may be better to separately fill in the initially empty values ​​and too large positive values. This is more a suggestion for thought, not a mandatory recommendation.
</div>

[RESPONSE TO REMARKS] Thank you - I very much wanted to consult this point. 
I wanted to distinguish between "empty values" and "high positive values" ("unknown"), but I didn't know how. 

In this project, I did not need to do any calculations on the 'days_employed' column. 
<br>The correct way, as I learned, is to handle these 3445 high positive values as outliers by reserving them in a separate dataframe of their own, and then removing them from the original dataframe. This way, the ratio of missing values will not increase significantly. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success #2:</b> I agree, this approach is good
</div>

**Handle the missing values in the 'total_income' column.**

Filling the 'total_income' values with the median of the column will change the data significantly. The data are probably missing because the customers did not work or did not want to reveal the information (i.e. MNAR). I will handle them as a case where no data were provided. 

In [137]:
# So, fill the 'total_income' column with zeros where there is NaN. 
data['total_income'] = data['total_income'].fillna(0)

# Verify it worked. 
#data.total_income.isnull().sum()

### Conclusion

The 'days_employed' and 'total_income' columns are the only columns with missing values. 
The two columns are missing values in exactly the same rows. Perhaps, customers did not want to share the information?
The rows with missing values account for approx. 10% of the total rows in the dataset.

'days_employed'
<br>a) 2174 missing values containing NaN
<br>-> Filled them with 0 rather than, say the median, since I felt I should not invent data where there is none. 
<br>
<br>b) 3445 high positive values
<br>-> Filled them with 0 to reflect the industry's convention in the use of high positive values, and
<br>I should not invent data where there is none. That will change the general characteristics of the dataset significantly. 
<br>
<br>c) 15906 (=21525-(2174+3445)) negative values.
<br>-> These are the values that are relevant to our research. 
<br>
<br>After filling the high positive values, the ratio of the rows with missing values increased to 26%. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Good points!
</div>

### Data type replacement

**Convert 'days_employed' to number of years.**

It makes more sense to display number of years rounded to the whole number.

In [138]:
# Change the data type of 'days_employed_years' from float to int.
data['days_employed_years'] = data['days_employed_years'].astype(int)

# Verify it worked. 
#data['days_employed_years']

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> +
</div>

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Code verifying is a good idea, but in the final version, it is better to remove the data output. Your code will become compact and fit in one cell.

</div>


**Convert 'debt' from integer to boolean.**

It makes more sense to use boolean to represent "a customer paid back a loan" and "a customer failed to pay back a loan".

In [139]:
# Change the data type of 'debt' from int to boolean.
data['debt'] = data['debt'].astype(bool)

# Verify it worked. 
#data['debt'].value_counts()

**Rename 'dob_years' to 'age'.**

In [140]:
# Rename 'dob_years' to 'age' for ease of understanding. 
data.set_axis(['children', 'days_employed', 'age', 'education', 'education_id', 'family_status', 'family_status_id', 'gender', 'income_type', 'debt', 'total_income', 'purpose', 'days_employed_years'], axis='columns', inplace=True)

# Verify it worked. 
#data.info()

**Convert illogical values in 'children' to logical guesses.**

In [141]:
# Check the count for each unique value.
data['children'].value_counts()

 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64

[Observation] There are 47 entries for '-1' and 76 entries for '20'.
After the conversions below, there ought to be:
* -1: 47 + 4818 = 4865 entries
* 20: 76 + 2055 = 2131 entries

In [143]:
# Convert all the '-1' entries to '1'. 
data.loc[data['children'] == -1, 'children'] = 1

In [145]:
# Similarly, convert all the '20' entries to '2'. 
data.loc[data['children'] == 20, 'children'] = 2

# Verify it worked.
#data['children'].value_counts()

[Observation] 4865 - OK; 2131 - OK

### Conclusion

The following modifications were made to enhance ease of understanding and calculation:
<br>
<br>= Data type conversion =
<br>'days_employed' 
* Changed from float to int.
* Converted negative to positive and expressed as number of years, rounded off to the nearest one

<br>'debt'
* Changed from int to boolean.
* Easier to understand to ask the question, "did the customer pay back a loan on time?" and then to ansewr "True" or "False".

= Renaming =
<br>'dob_years'
* Renamed 'dob_years' to 'age'. 

= Value correction =
<br>'children'
* Changed -1 to 1.
* Changed 20 to 2.

<br>'dob_years'
<br>[QUESTION] I did not change the value for those with the '0' entry. My guess is that they are not eligible for a loan because of their age. I would like to leave the data since the project does not relate to the age factor, and the data can provide valuable insights on the history of loan repayment with regard to other variables. Is this OK?

<div class="alert alert-danger" style="box-shadow: 4px 4px 4px">
<s><b>Needs fixing:</b> As you noted earlier, there are illogical values ​​in the children column. They should be processed at this stage. Also, take a closer look at the rest of the columns, somewhere else there may be similar errors that need to be corrected</s>
</div>

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success #2:</b> I agree, this approach is good. Keep in mind that usually such values ​​must be processed (replaced correctly or dropped). But sometimes with sufficient argumentation, you can leave them
</div>

### Processing duplicates

**Take care of the most obvious possible cause for duplicates - 'education'.**

In [146]:
# Standardize the 'education' values to lowercase. 
data['education'] = data['education'].str.lower()

# Verify it worked. 
#data.education.value_counts()

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Nice approach!
</div>

**Now onto identical repetitions of entire rows.**

In [147]:
# Count the number of duplicates.
data.duplicated().sum()

71

[Observation] There are 71 duplicates where the entire rows are identical "column for column". 

In [148]:
# View the duplicate rows based on all columns. 
data[data.duplicated()]

children  days_employed  age            education  education_id  \
2849          0            NaN   41  secondary education             1   
3290          0            NaN   58  secondary education             1   
4182          1            NaN   34    bachelor's degree             0   
4851          0            NaN   60  secondary education             1   
5557          0            NaN   58  secondary education             1   
...         ...            ...  ...                  ...           ...   
20702         0            NaN   64  secondary education             1   
21032         0            NaN   60  secondary education             1   
21132         0            NaN   47  secondary education             1   
21281         1            NaN   30    bachelor's degree             0   
21415         0            NaN   54  secondary education             1   

           family_status  family_status_id gender income_type   debt  \
2849             married                 0      F    employee  False   
3290   civil partnership                 1      F     retiree  False   
4182   civil partnership                 1      F    employee  False   
4851   civil partnership                 1      F     retiree  False   
5557   civil partnership                 1      F     retiree  False   
...                  ...               ...    ...         ...    ...   
20702            married                 0      F     retiree  False   
21032            married                 0      F     retiree  False   
21132            married                 0      F    employee  False   
21281            married                 0      F    employee  False   
21415            married                 0      F     retiree  False   

       total_income                              purpose  days_employed_years  
2849            0.0  purchase of the house for my family                    0  
3290            0.0                    to have a wedding                    0  
4182            0.0                     wedding ceremony                    0  
4851            0.0                     wedding ceremony                    0  
5557            0.0                    to have a wedding                    0  
...             ...                                  ...                  ...  
20702           0.0              supplementary education                    0  
21032           0.0                   to become educated                    0  
21132           0.0                   housing renovation                    0  
21281           0.0           buy commercial real estate                    0  
21415           0.0                 housing transactions                    0  

[71 rows x 13 columns]

[Observation] The duplicates were probably caused either by automatically importing them from another system, or more than one clerk working on the same customers' forms. 
It is highly unlikely that multiple people made loan requests that are identical "column for column". 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Good reasoning 👍
</div>

In [149]:
# So remove the duplicates and reset the indices. 
data = data.drop_duplicates().reset_index(drop=True)

# Verify it worked. 
#data.duplicated().sum()

[Observation] there are no more duplicates in the dataset. 

In [150]:
# Check the size of the dataset.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21454 entries, 0 to 21453
Data columns (total 13 columns):
children               21454 non-null int64
days_employed          15906 non-null float64
age                    21454 non-null int64
education              21454 non-null object
education_id           21454 non-null int64
family_status          21454 non-null object
family_status_id       21454 non-null int64
gender                 21454 non-null object
income_type            21454 non-null object
debt                   21454 non-null bool
total_income           21454 non-null float64
purpose                21454 non-null object
days_employed_years    21454 non-null int64
dtypes: bool(1), float64(2), int64(5), object(5)
memory usage: 2.0+ MB


[Observation] After removing the duplicates, there are now 21454 rows in total. 

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Answering your question:
        <br> * It's ok, you don't have to save duplicates


</div>

[RESPONSE TO REMARKS] understood. I will not save the data in a new dataset after removing duplicates.

### Conclusion

71 duplicates were found where the entire rows were identical "column for column". 
They were probably caused either by the rows being automatically imported from another system, or by more than one clerk working on the same customers' forms. 
It is highly unlikely that multiple people made loan requests that are identical "column for column", and therefore were deemed safe to remove them. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Well done! You are one step closer to completion
</div>

### Categorizing Data

In [151]:
# To get a general idea, check the ratio of customers who paid off a loan on time to those who did not. 
data.debt.value_counts()

False    19713
True      1741
Name: debt, dtype: int64

[Observation] out of all 21454 customers, 91.88% (= 19713 / 21454) have managed to repay a loan on time whereas 8.12% did not. 

Since what and how to categorize depends on the question, I will study each question in turn.

**[Question] Is there a connection between having kids and repaying a loan on time?**

To answer this question, I will create a pivot table with the 'children' as the index and the 'debt' as the column. 

In [152]:
# Note that there are no more '-1' and '20' entries. 
data.children.unique()

array([1, 0, 3, 2, 4, 5])

In [154]:
# Categorize 'children' into groups as follows:
# o 'children'=0: "Have no children"
# o 'children'=1: "Have 1 child"
# o 'children'=2: "Have 2 children"
# o 'children'=3: "Have 3 children"
# o 'children'=4: "Have 4 children"
# o 'children'=5: "Have 5 children" 
def count_children(number):
    if number == 0:
        return '0'
    elif number == 1:
        return '1'
    elif number == 2:
        return '2'
    elif number == 3:
        return '3'
    elif number == 4:
        return '4'
    else: 
        return '5' # i.e. num = 5

# Verify it works.
#print(count_children(0))
#print(count_children(1))
#print(count_children(2))
#print(count_children(3))
#print(count_children(4))
#print(count_children(5))

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> What about 20 kids? If this is an artifact, then it is worth somehow processing it at an earlier stage.


</div>

In [156]:
# Assign each row to a "child_group" category by applying count_children() to the dataset. 
data['children_group'] = data['children'].apply(count_children)

# View the first 10 rows.
#data.head(10)

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> 
    Well done for using the apply method
</div>

In [157]:
# Check the ratio of customers who paid off a loan on time to those who did not, grouped by the number of children they have.
debt_vs_children = data.pivot_table(index = 'children_group', columns = 'debt', values='children', aggfunc = 'count', margins = True).reset_index()

# View the pivot table. 
debt_vs_children

debt children_group    False    True    All
0                 0  13028.0  1063.0  14091
1                 1   4410.0   445.0   4855
2                 2   1926.0   202.0   2128
3                 3    303.0    27.0    330
4                 4     37.0     4.0     41
5                 5      9.0     NaN      9
6               All  19713.0  1741.0  21454

**[Question] Is there a connection between marital status and repaying a loan on time?**

To answer this question, I will create a pivot table with the 'family_status' as the index and the 'debt' as the column.

In [159]:
# Check the ratio of customers who paid off a loan on time to those who did not, grouped by their family status.
debt_vs_family_status = data.pivot_table(index = 'family_status', columns = 'debt', values = 'family_status_id', aggfunc='count', margins = True).reset_index()

# View the pivot table. 
debt_vs_family_status

debt      family_status  False  True    All
0     civil partnership   3763   388   4151
1              divorced   1110    85   1195
2               married  11408   931  12339
3             unmarried   2536   274   2810
4       widow / widower    896    63    959
5                   All  19713  1741  21454

In [160]:
# The family status together with the number of children may affect the ability to repay a loan. 
debt_vs_children_and_family_status = data.pivot_table(index = ['family_status', 'children_group'], columns = 'debt', values='family_status_id', aggfunc = 'count', margins = True).reset_index()

# View the pivot table. 
debt_vs_children_and_family_status.fillna(0)

debt      family_status children_group    False    True    All
0     civil partnership              0   2501.0   229.0   2730
1     civil partnership              1    882.0   118.0   1000
2     civil partnership              2    322.0    33.0    355
3     civil partnership              3     48.0     8.0     56
4     civil partnership              4      8.0     0.0      8
5     civil partnership              5      2.0     0.0      2
6              divorced              0    729.0    55.0    784
7              divorced              1    295.0    21.0    316
8              divorced              2     75.0     8.0     83
9              divorced              3     10.0     1.0     11
10             divorced              4      1.0     0.0      1
11              married              0   6952.0   516.0   7468
12              married              1   2757.0   247.0   3004
13              married              2   1434.0   148.0   1582
14              married              3    232.0    17.0    249
15              married              4     26.0     3.0     29
16              married              5      7.0     0.0      7
17            unmarried              0   2052.0   210.0   2262
18            unmarried              1    402.0    52.0    454
19            unmarried              2     74.0    10.0     84
20            unmarried              3      7.0     1.0      8
21            unmarried              4      1.0     1.0      2
22      widow / widower              0    794.0    53.0    847
23      widow / widower              1     74.0     7.0     81
24      widow / widower              2     21.0     3.0     24
25      widow / widower              3      6.0     0.0      6
26      widow / widower              4      1.0     0.0      1
27                  All                 19713.0  1741.0  21454

**[Question] Is there a connection between income level and repaying a loan on time?**

To answer this question, I will create a pivot table with the 'income_level' as the index and the 'debt' as the column.

First, categorize 'total_income' values into "income levels" to remove redundant details. 
<br> Take into account: min = 3306.762000; max = 362496.645000; interval = 10K; include the 'Data not provided' category
<br>Display '1000' as 'K' to present the data in a concise manner. 

In [162]:
def assign_income_level(amount):
    if amount == 0:
        return 'Data not provided'
    elif amount < 5000:
        return '< 5K'
    elif amount < 15000:
        return '5K - 15K'
    elif amount < 25000:
        return '15K - 25K'
    elif amount < 35000:
        return '25K - 35K'
    elif amount < 45000:
        return '35K - 45K'
    elif amount < 55000:
        return '45K - 55K'
    elif amount < 65000:
        return '55K - 65K'
    elif amount < 75000:
        return '55K - 75K'
    elif amount < 85000:
        return '75K - 85K'
    elif amount < 95000:
        return '85K - 95K'
    elif amount < 105000:
        return '95K - 105K'
    elif amount < 115000:
        return '105K - 115K'
    elif amount < 125000:
        return '115K - 125K'
    elif amount < 135000:
        return '125K - 135K'
    elif amount < 145000:
        return '135K - 145K'
    elif amount < 155000:
        return '145K - 155K'
    elif amount < 165000:
        return '155K - 165K'
    elif amount < 175000:
        return '164K - 175K'
    elif amount < 185000:
        return '174K - 185K'    
    elif amount < 195000:
        return '184K - 195K'    
    elif amount < 205000:
        return '194K - 205K'    
    elif amount < 215000:
        return '204K - 215K'    
    elif amount < 225000:
        return '214K - 225K'    
    elif amount < 235000:
        return '224K - 235K'    
    elif amount < 245000:
        return '234K - 245K' 
    elif amount < 255000:
        return '244K - 255K'    
    elif amount < 265000:
        return '254K - 265K'        
    elif amount < 275000:
        return '264K - 275K'        
    elif amount < 285000:
        return '274K - 285K'   
    elif amount < 295000:
        return '284K - 295K'       
    elif amount < 305000:
        return '294K - 305K'       
    elif amount < 315000:
        return '304K - 315K'  
    elif amount < 325000:
        return '314K - 325K'  
    elif amount < 335000:
        return '324K - 335K'  
    elif amount < 345000:
        return '334K - 345K'  
    elif amount < 355000:
        return '344K - 355K'      
    elif amount < 365000:
        return '354K - 365K'  
    elif amount < 375000:
        return '364K - 375K'      
    else:
        return 'Data not provided' # i.e. amount == 0

# Check the function works.
#print(assign_income_level(0))
#print(assign_income_level(3471.216))
#print(assign_income_level(8635.452))
#print(assign_income_level(12331.077))
#print(assign_income_level(21952.103))
#print(assign_income_level(32489.952))
#print(assign_income_level(43345.667))
#print(assign_income_level(54294.355))
#print(assign_income_level(60972.258))
#print(assign_income_level(73249.354))
#print(assign_income_level(84050.762))
#print(assign_income_level(99944.952))
#print(assign_income_level(100422.296))
#print(assign_income_level(112084.059))
#print(assign_income_level(121411.489))
#print(assign_income_level(130009.491))
#print(assign_income_level(147343.635))
#print(assign_income_level(153349.533))
#print(assign_income_level(160716.231))
#print(assign_income_level(174259.249))
#print(assign_income_level(180613.801))
#print(assign_income_level(195686.797))
#print(assign_income_level(205804.96))
#print(assign_income_level(216039.297))
#print(assign_income_level(228469.514))
#print(assign_income_level(234579.617))
#print(assign_income_level(248184.463))
#print(assign_income_level(255618.158))
#print(assign_income_level(264402.943))
#print(assign_income_level(273809.483))
#print(assign_income_level(286204.162))
#print(assign_income_level(295804.96))
#print(assign_income_level(312136.354))
#print(assign_income_level(322136.354))
#print(assign_income_level(332136.354))
#print(assign_income_level(342136.354))
#print(assign_income_level(352136.354))
#print(assign_income_level(362496.645))

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Some kind of bulky cell, don't you think? I would shorten the conclusion: it is superfluous

</div>

In [163]:
# Assign each row to an "income_level" category by applying assign_income_level() to the dataset. 
data['income_level'] = data['total_income'].apply(assign_income_level)

# View the first 10 rows.
data.head(10)

children  days_employed  age            education  education_id  \
0         1   -8437.673028   42    bachelor's degree             0   
1         1   -4024.803754   36  secondary education             1   
2         0   -5623.422610   33  secondary education             1   
3         3   -4124.747207   32  secondary education             1   
4         0            NaN   53  secondary education             1   
5         0    -926.185831   27    bachelor's degree             0   
6         0   -2879.202052   43    bachelor's degree             0   
7         0    -152.779569   50  secondary education             1   
8         2   -6929.865299   35    bachelor's degree             0   
9         0   -2188.756445   41  secondary education             1   

       family_status  family_status_id gender income_type   debt  \
0            married                 0      F    employee  False   
1            married                 0      F    employee  False   
2            married                 0      M    employee  False   
3            married                 0      M    employee  False   
4  civil partnership                 1      F     retiree  False   
5  civil partnership                 1      M    business  False   
6            married                 0      F    business  False   
7            married                 0      M    employee  False   
8  civil partnership                 1      F    employee  False   
9            married                 0      M    employee  False   

   total_income                              purpose  days_employed_years  \
0     40620.102                purchase of the house                   23   
1     17932.802                         car purchase                   11   
2     23341.752                purchase of the house                   15   
3     42820.568              supplementary education                   11   
4     25378.572                    to have a wedding                    0   
5     40922.170                purchase of the house                    2   
6     38484.156                 housing transactions                    7   
7     21731.829                            education                    0   
8     15337.093                     having a wedding                   18   
9     23108.150  purchase of the house for my family                    5   

  children_group income_level  
0              1    35K - 45K  
1              1    15K - 25K  
2              0    15K - 25K  
3              3    35K - 45K  
4              0    25K - 35K  
5              0    35K - 45K  
6              0    35K - 45K  
7              0    15K - 25K  
8              2    15K - 25K  
9              0    15K - 25K

In [164]:
# Check the ratio of customers who paid off a loan on time to those who did not, grouped by their income level.
debt_vs_income_level = data.pivot_table(index = 'income_level', columns = 'debt', values='total_income', aggfunc = 'count', margins = True).reset_index()

# View the pivot table. 
debt_vs_income_level

debt       income_level    False    True    All
0           105K - 115K     29.0     1.0     30
1           115K - 125K      9.0     NaN      9
2           125K - 135K      6.0     1.0      7
3           135K - 145K      6.0     1.0      7
4           145K - 155K      4.0     NaN      4
5           155K - 165K      4.0     1.0      5
6             15K - 25K   6407.0   598.0   7005
7           164K - 175K      4.0     NaN      4
8           174K - 185K      3.0     NaN      3
9           184K - 195K      1.0     NaN      1
10          194K - 205K      3.0     NaN      3
11          204K - 215K      1.0     NaN      1
12          214K - 225K      1.0     NaN      1
13          224K - 235K      1.0     NaN      1
14          244K - 255K      1.0     NaN      1
15          254K - 265K      1.0     NaN      1
16            25K - 35K   4150.0   385.0   4535
17          264K - 275K      2.0     NaN      2
18          274K - 285K      1.0     NaN      1
19          344K - 355K      NaN     1.0      1
20          354K - 365K      1.0     NaN      1
21            35K - 45K   2051.0   158.0   2209
22            45K - 55K    854.0    70.0    924
23            55K - 65K    408.0    33.0    441
24            55K - 75K    193.0    13.0    206
25             5K - 15K   3421.0   296.0   3717
26            75K - 85K    110.0     6.0    116
27            85K - 95K     56.0     2.0     58
28           95K - 105K     28.0     3.0     31
29                 < 5K     24.0     2.0     26
30    Data not provided   1933.0   170.0   2103
31                  All  19713.0  1741.0  21454

[Observation] Income levels above 115K can be put in a single group because the distribution is small. 

In [166]:
# Adjust the interval to remove redundant details.
def assign_income_level(amount):
    if amount == 0:
        return 'Data not provided'
    elif amount < 5000:
        return '< 5K'
    elif amount < 15000:
        return '5K - 15K'
    elif amount < 25000:
        return '15K - 25K'
    elif amount < 35000:
        return '25K - 35K'
    elif amount < 45000:
        return '35K - 45K'
    elif amount < 55000:
        return '45K - 55K'
    elif amount < 65000:
        return '55K - 65K'
    elif amount < 75000:
        return '55K - 75K'
    elif amount < 85000:
        return '75K - 85K'
    elif amount < 95000:
        return '85K - 95K'
    elif amount < 105000:
        return '95K - 105K'
    elif amount < 115000:
        return '105K - 115K'
    else:
        return '> 115K' # i.e. amount > 115000

# Check the function works.
#print(assign_income_level(121411.489))
#print(assign_income_level(130009.491))
#print(assign_income_level(147343.635))
#print(assign_income_level(153349.533))
#print(assign_income_level(160716.231))
#print(assign_income_level(174259.249))
#print(assign_income_level(180613.801))
#print(assign_income_level(195686.797))
#print(assign_income_level(205804.96))
#print(assign_income_level(216039.297))
#print(assign_income_level(228469.514))
#print(assign_income_level(234579.617))
#print(assign_income_level(248184.463))
#print(assign_income_level(255618.158))
#print(assign_income_level(264402.943))
#print(assign_income_level(273809.483))
#print(assign_income_level(286204.162))
#print(assign_income_level(295804.96))
#print(assign_income_level(312136.354))
#print(assign_income_level(322136.354))
#print(assign_income_level(332136.354))
#print(assign_income_level(342136.354))
#print(assign_income_level(352136.354))
#print(assign_income_level(362496.645))

In [167]:
# Assign each row to an "income_level" category by applying assign_income_level() to the dataset. 
data['income_level'] = data['total_income'].apply(assign_income_level)

# View the first 10 rows.
data.head(10)

children  days_employed  age            education  education_id  \
0         1   -8437.673028   42    bachelor's degree             0   
1         1   -4024.803754   36  secondary education             1   
2         0   -5623.422610   33  secondary education             1   
3         3   -4124.747207   32  secondary education             1   
4         0            NaN   53  secondary education             1   
5         0    -926.185831   27    bachelor's degree             0   
6         0   -2879.202052   43    bachelor's degree             0   
7         0    -152.779569   50  secondary education             1   
8         2   -6929.865299   35    bachelor's degree             0   
9         0   -2188.756445   41  secondary education             1   

       family_status  family_status_id gender income_type   debt  \
0            married                 0      F    employee  False   
1            married                 0      F    employee  False   
2            married                 0      M    employee  False   
3            married                 0      M    employee  False   
4  civil partnership                 1      F     retiree  False   
5  civil partnership                 1      M    business  False   
6            married                 0      F    business  False   
7            married                 0      M    employee  False   
8  civil partnership                 1      F    employee  False   
9            married                 0      M    employee  False   

   total_income                              purpose  days_employed_years  \
0     40620.102                purchase of the house                   23   
1     17932.802                         car purchase                   11   
2     23341.752                purchase of the house                   15   
3     42820.568              supplementary education                   11   
4     25378.572                    to have a wedding                    0   
5     40922.170                purchase of the house                    2   
6     38484.156                 housing transactions                    7   
7     21731.829                            education                    0   
8     15337.093                     having a wedding                   18   
9     23108.150  purchase of the house for my family                    5   

  children_group income_level  
0              1    35K - 45K  
1              1    15K - 25K  
2              0    15K - 25K  
3              3    35K - 45K  
4              0    25K - 35K  
5              0    35K - 45K  
6              0    35K - 45K  
7              0    15K - 25K  
8              2    15K - 25K  
9              0    15K - 25K

In [169]:
# Check the ratio of customers who paid off a loan on time to those who did not, grouped by their income level.
debt_vs_income_level = data.pivot_table(index = 'income_level', columns = 'debt', values='total_income', aggfunc = 'count', margins = True).reset_index()

# View the pivot table. 
debt_vs_income_level

debt       income_level  False  True    All
0           105K - 115K     29     1     30
1             15K - 25K   6407   598   7005
2             25K - 35K   4150   385   4535
3             35K - 45K   2051   158   2209
4             45K - 55K    854    70    924
5             55K - 65K    408    33    441
6             55K - 75K    193    13    206
7              5K - 15K   3421   296   3717
8             75K - 85K    110     6    116
9             85K - 95K     56     2     58
10           95K - 105K     28     3     31
11                 < 5K     24     2     26
12               > 115K     49     4     53
13    Data not provided   1933   170   2103
14                  All  19713  1741  21454

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Well done for making a pivot table: the result is clear
</div>

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Answering your question:
        <br> * Your approach to solving this problem is good enough. I would not change anything in it
</div>

[RESPONSE TO REMARK] Understood. Thank you. 

**[Question] How do different loan purposes affect on-time loan repayment?**

To answer this question, I will analyze the texts in the 'purpose' column to find categories.

In [170]:
# First, obtain a unique list of the column values.
data.purpose.value_counts()

wedding ceremony                            791
having a wedding                            768
to have a wedding                           765
real estate transactions                    675
buy commercial real estate                  661
housing transactions                        652
buying property for renting out             651
transactions with commercial real estate    650
housing                                     646
purchase of the house                       646
purchase of the house for my family         638
construction of own property                635
property                                    633
transactions with my real estate            627
building a real estate                      624
buy real estate                             621
purchase of my own house                    620
building a property                         619
housing renovation                          607
buy residential real estate                 606
buying my own car                       

[Observation] The values can be classified into 4 main categories: wedding, real estate, car, education

Now find a list of all the words related to each category.

In [171]:
# Combine all the texts in the 'purpose' column into a single string. Do not include repeated values. 
purposes = ' '.join(data.purpose.unique())

# Print the string. 
print(purposes)

purchase of the house car purchase supplementary education to have a wedding housing transactions education having a wedding purchase of the house for my family buy real estate buy commercial real estate buy residential real estate construction of own property property building a property buying a second-hand car buying my own car transactions with commercial real estate building a real estate housing transactions with my real estate cars to become educated second-hand car purchase getting an education car wedding ceremony to get a supplementary education purchase of my own house real estate transactions getting higher education to own a car purchase of a car profile education university education buying property for renting out to buy a car housing renovation going to university


In [172]:
# Convert 'purposes' into a list or words.
words = nltk.word_tokenize(purposes)
print(words)

['purchase', 'of', 'the', 'house', 'car', 'purchase', 'supplementary', 'education', 'to', 'have', 'a', 'wedding', 'housing', 'transactions', 'education', 'having', 'a', 'wedding', 'purchase', 'of', 'the', 'house', 'for', 'my', 'family', 'buy', 'real', 'estate', 'buy', 'commercial', 'real', 'estate', 'buy', 'residential', 'real', 'estate', 'construction', 'of', 'own', 'property', 'property', 'building', 'a', 'property', 'buying', 'a', 'second-hand', 'car', 'buying', 'my', 'own', 'car', 'transactions', 'with', 'commercial', 'real', 'estate', 'building', 'a', 'real', 'estate', 'housing', 'transactions', 'with', 'my', 'real', 'estate', 'cars', 'to', 'become', 'educated', 'second-hand', 'car', 'purchase', 'getting', 'an', 'education', 'car', 'wedding', 'ceremony', 'to', 'get', 'a', 'supplementary', 'education', 'purchase', 'of', 'my', 'own', 'house', 'real', 'estate', 'transactions', 'getting', 'higher', 'education', 'to', 'own', 'a', 'car', 'purchase', 'of', 'a', 'car', 'profile', 'educati

In [173]:
# Remove duplicates to shorten the list as much as possible for optimization. 
all_words = []

for word in words:
    if word not in all_words:
        all_words.append(word)

# Verify it worked.
print(all_words)

['purchase', 'of', 'the', 'house', 'car', 'supplementary', 'education', 'to', 'have', 'a', 'wedding', 'housing', 'transactions', 'having', 'for', 'my', 'family', 'buy', 'real', 'estate', 'commercial', 'residential', 'construction', 'own', 'property', 'building', 'buying', 'second-hand', 'with', 'cars', 'become', 'educated', 'getting', 'an', 'ceremony', 'get', 'higher', 'profile', 'university', 'renting', 'out', 'renovation', 'going']


In [174]:
# Remove stop words to shorten the list as much as possible for optimization. 
stop_words = set(stopwords.words('english'))

filtered_list = []
 
for word in all_words:
    if word not in stop_words:
        filtered_list.append(word)

print(filtered_list)

['purchase', 'house', 'car', 'supplementary', 'education', 'wedding', 'housing', 'transactions', 'family', 'buy', 'real', 'estate', 'commercial', 'residential', 'construction', 'property', 'building', 'buying', 'second-hand', 'cars', 'become', 'educated', 'getting', 'ceremony', 'get', 'higher', 'profile', 'university', 'renting', 'renovation', 'going']


In [176]:
# Find and save the lemma of each word.
lemmas = [wordnet_lemma.lemmatize(word, pos = 'n') for word in filtered_list]
lemmas_v = [wordnet_lemma.lemmatize(word, pos = 'v') for word in lemmas]

# Verify it worked. 
print(lemmas_v)

['purchase', 'house', 'car', 'supplementary', 'education', 'wed', 'house', 'transaction', 'family', 'buy', 'real', 'estate', 'commercial', 'residential', 'construction', 'property', 'build', 'buy', 'second-hand', 'car', 'become', 'educate', 'get', 'ceremony', 'get', 'higher', 'profile', 'university', 'rent', 'renovation', 'go']


<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success #2:</b> 
    
Here ⬆⬆⬆ you can create list of lemmas based on filtered_list excluding 'wedding'. Then you can manually add 'wedding' to the resulting list lemmas_v. But after finding the stem, wedding becomes wed
</div>

[Comment] Not applying pos = 'a' (adjective) or 'r' (adverb) in order to keep words like 'higher'. 

In [177]:
# Find the stem of each word.
stems = [english_stemmer.stem(word) for word in lemmas_v]

# Verify it worked. 
print(stems)

['purchas', 'hous', 'car', 'supplementari', 'educ', 'wed', 'hous', 'transact', 'famili', 'buy', 'real', 'estat', 'commerci', 'residenti', 'construct', 'properti', 'build', 'buy', 'second-hand', 'car', 'becom', 'educ', 'get', 'ceremoni', 'get', 'higher', 'profil', 'univers', 'rent', 'renov', 'go']


In [69]:
# Remove duplicates again to shorten the list as much as possible for optimization. 
all_words = []

for word in stems:
    if word not in all_words:
        all_words.append(word)

# Verify it worked.
print(all_words)

['purchas', 'hous', 'car', 'supplementari', 'educ', 'wed', 'transact', 'famili', 'buy', 'real', 'estat', 'commerci', 'residenti', 'construct', 'properti', 'build', 'second-hand', 'becom', 'get', 'ceremoni', 'higher', 'profil', 'univers', 'rent', 'renov', 'go']


[QUESTION] How can I keep 'wedding' (before lemmatization) but unify 'car' and 'cars' (after lemmatization)?

In [182]:
# Define a dictionary and fill the values for each category from the list above.
categories = {
        'wedding': ['wed', 'ceremon'],
        'real estate': ['purchas', 'hous', 'transact', 'buy', 'famil', 'estate', 'commerci', 'residenti', 'construct', 'propert', 'build', 'rent', 'renov'],
        'car': ['car', 'second-hand'],
        'education': ['educ', 'supplementar', 'becom', 'get', 'higher', 'profil', 'univers', 'go']
}

# View the dictionary. 
categories

{'wedding': ['wed', 'ceremon'],
 'real estate': ['purchas',
  'hous',
  'transact',
  'buy',
  'famil',
  'estate',
  'commerci',
  'residenti',
  'construct',
  'propert',
  'build',
  'rent',
  'renov'],
 'car': ['car', 'second-hand'],
 'education': ['educ',
  'supplementar',
  'becom',
  'get',
  'higher',
  'profil',
  'univers',
  'go']}

Assign a 'purpose' value to a purpose category. 

In [183]:
# Make a copy of the 'purpose' column so as not to overwite the values.
purpose_copy = data['purpose']
data['purpose_category'] = purpose_copy

# Verify it worked.
data.purpose_category.head(10)

0                  purchase of the house
1                           car purchase
2                  purchase of the house
3                supplementary education
4                      to have a wedding
5                  purchase of the house
6                   housing transactions
7                              education
8                       having a wedding
9    purchase of the house for my family
Name: purpose_category, dtype: object

[QUESTION] All the attemps below issued a SettingWithCopyWarning warning. These are all legitimate operations. So why?
<br>data.loc[data['purpose'], 'purpose_copy'] = data['purpose']
<br>data.purpose_copy = data.purpose_copy.fillna(data.purpose)
<br>data.purpose_copy = data.purpose.copy()

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Answering your question:
        <br> * Maybe this guide will help you
    <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html">Data Selecting</a><br>
</div>





[RESPONSE TO REMARKS] Thank you for sending me the reference. Now I need to digest the info. :)

In [184]:
# Check if the 'purpose' value is in the categories dictionary. 
for key, value in categories.items():
    filter_column = data['purpose_category'].str.contains('|'.join(value))
    data['purpose_category'][filter_column] = key

[QUESION] I do not want to overwrite the 'purpose' column so I made a copy and worked on that copy. 
<br>What is the way that Python will not issue a warning?

<div class="alert alert-warning" style="box-shadow: 4px 4px 4px">
<b>Remarks:</b> Answering your question:
    * Read the documentation carefully, there you will find all the answers
       <br> <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy">Returning versus a copy</a><br> 
</div>

[RESPONSE TO REMARKS] I have now included the 'import sys' lines in the project header. 

In [186]:
# View the first 10 rows of the dataset.
data.head(10)

children  days_employed  age            education  education_id  \
0         1   -8437.673028   42    bachelor's degree             0   
1         1   -4024.803754   36  secondary education             1   
2         0   -5623.422610   33  secondary education             1   
3         3   -4124.747207   32  secondary education             1   
4         0            NaN   53  secondary education             1   
5         0    -926.185831   27    bachelor's degree             0   
6         0   -2879.202052   43    bachelor's degree             0   
7         0    -152.779569   50  secondary education             1   
8         2   -6929.865299   35    bachelor's degree             0   
9         0   -2188.756445   41  secondary education             1   

       family_status  family_status_id gender income_type   debt  \
0            married                 0      F    employee  False   
1            married                 0      F    employee  False   
2            married                 0      M    employee  False   
3            married                 0      M    employee  False   
4  civil partnership                 1      F     retiree  False   
5  civil partnership                 1      M    business  False   
6            married                 0      F    business  False   
7            married                 0      M    employee  False   
8  civil partnership                 1      F    employee  False   
9            married                 0      M    employee  False   

   total_income                              purpose  days_employed_years  \
0     40620.102                purchase of the house                   23   
1     17932.802                         car purchase                   11   
2     23341.752                purchase of the house                   15   
3     42820.568              supplementary education                   11   
4     25378.572                    to have a wedding                    0   
5     40922.170                purchase of the house                    2   
6     38484.156                 housing transactions                    7   
7     21731.829                            education                    0   
8     15337.093                     having a wedding                   18   
9     23108.150  purchase of the house for my family                    5   

  children_group income_level purpose_category  
0              1    35K - 45K      real estate  
1              1    15K - 25K      real estate  
2              0    15K - 25K      real estate  
3              3    35K - 45K        education  
4              0    25K - 35K          wedding  
5              0    35K - 45K      real estate  
6              0    35K - 45K      real estate  
7              0    15K - 25K        education  
8              2    15K - 25K          wedding  
9              0    15K - 25K      real estate

In [187]:
# Check the ratio of customers who paid off a loan on time to those who did not, grouped by the corresponding purpose category.
debt_vs_purpose = data.pivot_table(index = 'purpose_category', columns = 'debt', values='purpose', aggfunc = 'count', margins = True).reset_index()

# View the pivot table. 
debt_vs_purpose

debt purpose_category  False  True    All
0                 car   1316   134   1450
1           education   3643   370   4013
2         real estate  12616  1051  13667
3             wedding   2138   186   2324
4                 All  19713  1741  21454

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Everything was done well, but the tables with the results are repeated. I would advise to combine them to make the solution more visual.
</div>



### Conclusion

What to categorize depends on what is being asked. 

<br>To find the relationship between the number of children and whether or not a loan was repaid, I thought it was important to present the data for each age group between 0 and 5. 

<br>Finding the relationship between the family status and whether or not a loan was repaid was starightforward, and I felt no need to do any custom categorization. 

<br>To find the relationship between the income levels and whether or not a loan was repaid, I used the minimum and maximum total income values as guides for the lower and upper boundaries of the range. I first set an interval of 10K, and found an unnecessary level of detail for above 115K. I grouped all the income levels above 115K and managed to reduce the number of levels. Also, I wanted to present those rows where the 'total_income' values were missing in a separate category of its own because I felt that there was a story there. 

<br>To find the relationship between the reason for asking for a loan (i.e. 'purpose') and whether or not a loan was repaid, I identified 4 main categories by looking at the unique values. I defined the categories as a dictionary and listed all the words commonly found in the 'purpose' with the help of tokenization, stemming and lemmatization. 

## Answer these questions

- Is there a relation between having kids and repaying a loan on time?

In [189]:
# Calculate the default rates. 
debt_vs_children['default_rate'] = (debt_vs_children[1] / debt_vs_children['All']) * 100

# View the pivot table with the default rate sorted in descending order. 
debt_vs_children.sort_values('default_rate', ascending = False).fillna(0)

debt children_group    False    True    All  default_rate
4                 4     37.0     4.0     41      9.756098
2                 2   1926.0   202.0   2128      9.492481
1                 1   4410.0   445.0   4855      9.165808
3                 3    303.0    27.0    330      8.181818
6               All  19713.0  1741.0  21454      8.115037
0                 0  13028.0  1063.0  14091      7.543822
5                 5      9.0     0.0      9      0.000000

### Conclusion

* Customers with no children have the lowest default rate at 7.54%, which is 0.58 percentage points below average. 
* Interestingly,all the  customers with 5 children manage to repay the loan on time, though the data volume is too small for it to be statistically viable.  
* Customers with 4 children have the highest default rate at 9.76%, which is above average by 1.64 percentage points. 
* However, the default rate is not directly proportional to the number of children. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Very interesting result, you did a good job with the data. Well done for using sorting!
</div>

- Is there a relation between marital status and repaying a loan on time?

In [190]:
# Calculate the default rates per family status. 
debt_vs_family_status['default_rate'] = (debt_vs_family_status[1] / debt_vs_family_status['All']) * 100

# View the pivot table with the default rate sorted in descending order. 
debt_vs_family_status.sort_values('default_rate', ascending = False)

debt      family_status  False  True    All  default_rate
3             unmarried   2536   274   2810      9.750890
0     civil partnership   3763   388   4151      9.347145
5                   All  19713  1741  21454      8.115037
2               married  11408   931  12339      7.545182
1              divorced   1110    85   1195      7.112971
4       widow / widower    896    63    959      6.569343

In [191]:
# Calculate the default rates per family status and the number of children in the family. 
debt_vs_children_and_family_status['default_rate'] = (debt_vs_children_and_family_status[1] / debt_vs_children_and_family_status['All']) * 100

# View the pivot table with the default rate sorted in descending order. 
debt_vs_children_and_family_status.sort_values('default_rate', ascending = False).fillna(0)

debt      family_status children_group    False    True    All  default_rate
21            unmarried              4      1.0     1.0      2     50.000000
3     civil partnership              3     48.0     8.0     56     14.285714
20            unmarried              3      7.0     1.0      8     12.500000
24      widow / widower              2     21.0     3.0     24     12.500000
19            unmarried              2     74.0    10.0     84     11.904762
1     civil partnership              1    882.0   118.0   1000     11.800000
18            unmarried              1    402.0    52.0    454     11.453744
15              married              4     26.0     3.0     29     10.344828
8              divorced              2     75.0     8.0     83      9.638554
13              married              2   1434.0   148.0   1582      9.355247
2     civil partnership              2    322.0    33.0    355      9.295775
17            unmarried              0   2052.0   210.0   2262      9.283820
9              divorced              3     10.0     1.0     11      9.090909
23      widow / widower              1     74.0     7.0     81      8.641975
0     civil partnership              0   2501.0   229.0   2730      8.388278
12              married              1   2757.0   247.0   3004      8.222370
27                  All                 19713.0  1741.0  21454      8.115037
6              divorced              0    729.0    55.0    784      7.015306
11              married              0   6952.0   516.0   7468      6.909480
14              married              3    232.0    17.0    249      6.827309
7              divorced              1    295.0    21.0    316      6.645570
22      widow / widower              0    794.0    53.0    847      6.257379
4     civil partnership              4      8.0     0.0      8      0.000000
5     civil partnership              5      2.0     0.0      2      0.000000
10             divorced              4      1.0     0.0      1      0.000000
16              married              5      7.0     0.0      7      0.000000
25      widow / widower              3      6.0     0.0      6      0.000000
26      widow / widower              4      1.0     0.0      1      0.000000

### Conclusion

* Customers whose spouse has deceased have the lowest default rate at 6.57%, 1.55 percentage points less than the average. 
* Customers who are single have the highest default rate at 9.75%, 1.64 percentage points above the average. 
* The average default rate is 8.12%, which concurs with the figure from the statistics regarding the number of children. 
* Statistically, single parents with four children have the highest default rate. Although this is not surprising, since there is only one such case recorded out of two, we will need a much larger number of records to be able to draw a statistically significant conclusion. Also, this should be treated as an outlier since its difference from the common law couples figure in the second place is way too large (50 in comparison to 14.29). 
* Interestingly enough, common law couples with the highest numbers of children seem to be very good at repaying a loan.
* It is also interesting to see that widows/widowers, married and divorced couples have the highest likelihood of paying off a loan successfully, despite the large number of children.

- Is there a relation between income level and repaying a loan on time?

In [192]:
# Calculate the default rates. 
debt_vs_income_level['default_rate'] = (debt_vs_income_level[1] / debt_vs_income_level['All']) * 100

# View the pivot table with the default rate sorted in descending order. 
debt_vs_income_level.sort_values('default_rate', ascending = False)

debt       income_level  False  True    All  default_rate
10           95K - 105K     28     3     31      9.677419
1             15K - 25K   6407   598   7005      8.536759
2             25K - 35K   4150   385   4535      8.489526
14                  All  19713  1741  21454      8.115037
13    Data not provided   1933   170   2103      8.083690
7              5K - 15K   3421   296   3717      7.963411
11                 < 5K     24     2     26      7.692308
4             45K - 55K    854    70    924      7.575758
12               > 115K     49     4     53      7.547170
5             55K - 65K    408    33    441      7.482993
3             35K - 45K   2051   158   2209      7.152558
6             55K - 75K    193    13    206      6.310680
8             75K - 85K    110     6    116      5.172414
9             85K - 95K     56     2     58      3.448276
0           105K - 115K     29     1     30      3.333333

In [193]:
# Check the median of the 'total_income' column.
median = data.total_income.median()

# View the median.
print('{:.2f}'.format(median))

21724.97


In [194]:
# Check the family status in the income level groups. 
income_level_vs_family_status = data.pivot_table(index = 'family_status', columns = 'income_level', values='family_status_id', aggfunc = 'count', margins = True).reset_index()

# View the pivot table. 
income_level_vs_family_status.fillna(0)

income_level      family_status  105K - 115K  15K - 25K  25K - 35K  35K - 45K  \
0             civil partnership          6.0     1378.0      865.0      428.0   
1                      divorced          0.0      376.0      262.0      127.0   
2                       married         18.0     3957.0     2651.0     1273.0   
3                     unmarried          6.0      961.0      594.0      297.0   
4               widow / widower          0.0      333.0      163.0       84.0   
5                           All         30.0     7005.0     4535.0     2209.0   

income_level  45K - 55K  55K - 65K  55K - 75K  5K - 15K  75K - 85K  85K - 95K  \
0                 189.0       79.0       36.0     707.0       17.0        8.0   
1                  55.0       26.0        8.0     211.0        9.0        4.0   
2                 551.0      269.0      126.0    2117.0       74.0       40.0   
3                 109.0       55.0       31.0     439.0       16.0        3.0   
4                  20.0       12.0        5.0     243.0        0.0        3.0   
5                 924.0      441.0      206.0    3717.0      116.0       58.0   

income_level  95K - 105K  < 5K  > 115K  Data not provided    All  
0                    3.0   7.0    12.0              416.0   4151  
1                    2.0   0.0     3.0              112.0   1195  
2                   19.0  17.0    31.0             1196.0  12339  
3                    6.0   2.0     6.0              285.0   2810  
4                    1.0   0.0     1.0               94.0    959  
5                   31.0  26.0    53.0             2103.0  21454

### Conclusion

* Customers in the 105K - 115K income level tend to have the lowest default rate at 3.33%. 
* Customers in the 95K - 105K income level tend to have the highest default rate at 9.68%. 
* In both income level groups above, the majority are married. 
* The majority (21.14%) are in the 15K - 35K income level and tend to have an above-average default rate at 8.52%. 
* The average default rate is 8.12%, which concurs with the figure from the statistics regarding the number of children and 
* the family status. 
* Higher income levels do not indicate lower default rates.  
* Customers who probably did not wish to provide the data have a just below average default rate at 8.08%. The vast majority are married. 
* With the median total income of 21724.97, the 15K - 25K income level group ranks in the second place, feeling the need to borrow, then finding themselves unable to repay the loan. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> Well done!
</div>

- How do different loan purposes affect on-time repayment of the loan?

In [195]:
# Calculate the default rates. 
debt_vs_purpose['default_rate'] = (debt_vs_purpose[1] / debt_vs_purpose['All']) * 100

# View the pivot table with the default rate sorted in descending order. 
debt_vs_purpose.sort_values('default_rate', ascending = False)

debt purpose_category  False  True    All  default_rate
0                 car   1316   134   1450      9.241379
1           education   3643   370   4013      9.220035
4                 All  19713  1741  21454      8.115037
3             wedding   2138   186   2324      8.003442
2         real estate  12616  1051  13667      7.690056

### Conclusion

* Customers who request a loan for automotive related purposes have the highest default rate at 9.24%. 
* Customers who request a loan for real estate related purposes have the lowest default rate at 7.69%. 
* The average default rate is 8.12%, which concurs with the figure from the statistics regarding the number of children, the family status and the income level. 

## General conclusion

We were given some data on loan applicants, including their marital status, how many children they have, the reason for them asking for a loan, together with their history on a previous loan request and whether or not they managed to repay it on time. 

<br>The analysis of the data showed that out of all the customers, 91.88% did manage to repay a loan on time. 

<br>Regarding the 8.12% who did not, we found the following: 
* Customers with no children had the lowest default rate, and single parents and common law couples with three or four children, the highest. There was no clear sign that the default rate increased predictably with the number of children. 
* Again, though there is only a handful of cases, all the customers other than those who are single parents had the highest likelihood of paying off a loan successfully, despite the large number of children.
* There were largely three groups of loan defaulters with above-average default rates, who were either married, common law couples or single parents, all with small number of children. 
* In terms of income levels, there seemed to be a fine line between the 105K - 115K and 95K - 105 groups, where the former had the lowest default rate in the chart, and the latter, the highest. In both income groups, the majority were married. 
* With the median total income of 21724.97, the majority of the loan requestors fell in the 15K - 35K income bracket, and had the second highest default rate.  
* On the whole, higher income levels did not indicate lower default rates.  
* Customers who probably did not wish to provide the data had a just-below-average default rate. The vast majority were married. 

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> You have done a great job! Your results are really impressive!
</div>

[Summary] The factors that lead to above-average default rates are as follows:
* Number of children: 4, 2, 1, 3
* Family status: unmarried, civil partnership
* Income level: 95K - 105K, 15K - 25K, 25K - 35K
* Words in purpose: car, education

<div class="alert alert-success" style="box-shadow: 4px 4px 4px">
<b>Success:</b> 👍
    More information about forecasting methods will be in the know, you will be interested)
</div>

However, if I "predict" the likelihood of a customer defaulting on a loan from the 'children', 'family_status', 'income_level' and 'purpose_category' variables, it does not match the actual values in 'debt'. 

* Number of customers who did not repay the loan on time (i.e. 'debt' == 1): 1741
* Number predicted from the 4 variables: 18388

Below are the calculations.

Define the dictionaries in terms of the factors leading to above-average default rates.

In [217]:
above_avg_rates_children_group = {'1': ['4', '2', '1', '3']}
above_avg_rates_family_status = {'1': ['unmarried', 'civil partnership']}
above_avg_rates_income_level = {'1': ['95K - 105K', '15K - 25K', '25K - 35K']}
above_avg_rates_purpose_category = {'1': ['car', 'education']}

Check whether the 'children_group' column values are in the designated dictionary or not.

In [219]:
# If it is not, it means the columm value is in the above-average default rate group. 
for key, value in above_avg_rates_children_group.items():
     filter_column = data['children_group'].str.contains('|'.join(value))
data['children_group_verdict'] = filter_column
data['children_group_verdict'] = data['children_group_verdict'].astype(int)

# Verify it worked. 
#data.children_group_verdict.head(10)

Check whether the 'family_status' column values are in the designated dictionary or not.

In [220]:
# If it is, it means the columm value is in the above-average default rate group. 
for key, value in above_avg_rates_family_status.items():
     filter_column = data['family_status'].str.contains('|'.join(value))
data['family_status_verdict'] = filter_column
data['family_status_verdict'] = data['family_status_verdict'].astype(int)

# Verify it worked. 
#data.family_status_verdict.head(10)

Check whether the 'income_level' column values are in the designated dictionary or not.

In [221]:
# If it is, it means the columm value is in the above-average default rate group. 
for key, value in above_avg_rates_income_level.items():
    filter_column = data['income_level'].str.contains('|'.join(value))
data['income_level_verdict'] = filter_column
data['income_level_verdict'] = data['income_level_verdict'].astype(int)

# Verify it worked. 
#data.income_level_verdict.head(10)

Check whether the 'purpose_category' column values are in the designated dictionary or not.

In [222]:
# If it is, it means the columm value is in the above-average default rate group. 
for key, value in above_avg_rates_purpose_category.items():
    filter_column = data['purpose_category'].str.contains('|'.join(value))
data['purpose_category_verdict'] = filter_column
data['purpose_category_verdict'] = data['purpose_category_verdict'].astype(int)

# Verify it worked.
#data.purpose_category_verdict.head(10)

In [240]:
# Add up the 4 columns and divide by 4 to calculate the overall likelihood of defaulting. Store the value in a new column. 
sum_column = data['children_group_verdict'] + data['family_status_verdict'] + data['income_level_verdict'] + data['purpose_category_verdict']
data['final_verdict'] = sum_column / 4

In [242]:
# Count the rows where the customer defaulted on a loan. 
data[data['debt'] == 1].count()

children                    1741
days_employed               1389
age                         1741
education                   1741
education_id                1741
family_status               1741
family_status_id            1741
gender                      1741
income_type                 1741
debt                        1741
total_income                1741
purpose                     1741
days_employed_years         1741
children_group              1741
income_level                1741
purpose_category            1741
children_group_verdict      1741
family_status_verdict       1741
income_level_verdict        1741
purpose_category_verdict    1741
final_verdict               1741
dtype: int64

In [244]:
# Count the rows where the 'final_verdict' predicted a non-zero default rate from 'children', 'family_status', 
# 'income_level' and 'purpose'.
data[data['final_verdict'] != 0.00].count()

children                    18388
days_employed               14196
age                         18388
education                   18388
education_id                18388
family_status               18388
family_status_id            18388
gender                      18388
income_type                 18388
debt                        18388
total_income                18388
purpose                     18388
days_employed_years         18388
children_group              18388
income_level                18388
purpose_category            18388
children_group_verdict      18388
family_status_verdict       18388
income_level_verdict        18388
purpose_category_verdict    18388
final_verdict               18388
dtype: int64

## Project Readiness Checklist

Put 'x' in the completed points. Then press Shift + Enter.

- [x]  file open;
- [x]  file examined;
- [x]  missing values defined;
- [x]  missing values are filled;
- [x]  an explanation of which missing value types were detected;
- [x]  explanation for the possible causes of missing values;
- [x]  an explanation of how the blanks are filled;
- [x]  replaced the real data type with an integer;
- [x]  an explanation of which method is used to change the data type and why;
- [x]  duplicates deleted;
- [x]  an explanation of which method is used to find and remove duplicates;
- [x]  description of the possible reasons for the appearance of duplicates in the data;
- [x]  data is categorized;
- [x]  an explanation of the principle of data categorization;
- [x]  an answer to the question "Is there a relation between having kids and repaying a loan on time?";
- [x]  an answer to the question " Is there a relation between marital status and repaying a loan on time?";
- [x]   an answer to the question " Is there a relation between income level and repaying a loan on time?";
- [x]  an answer to the question " How do different loan purposes affect on-time repayment of the loan?"
- [x]  conclusions are present on each stage;
- [x]  a general conclusion is made.